[package]
name = "ceph-safe-disk"
version = "0.1.0"
authors = ["Alberto Corona <ac@albertocorona.com>"]

[dependencies]
getopts = "0.2"
ansi_term = "0.7"
serde = "^0.9"
serde_derive = "^0.9"
serde_json = "^0.9"
users = "0.5"

[lib]
name = "ceph"
path = "lib/lib.rs"
